### ISSUE TITLE
java.lang.NoClassDefFoundError for com.ibm.cicsdev.bean.JZOSCommareaWrapper

### ISSUE THREAD

**Issue by ebarkow** [cicsdev/cics-java-jzosprog#1]
I was not able to get CICS (TS 5.1) to find JZOSCommareaWrapper.class in the EDUPGM.jar.
I ended up copying the JZOSCommareaWrapper.class file into the src directory and  it then worked.
this is the MANIFEST.MF file for the OSGI bundle:
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: %Bundle-Name
Bundle-SymbolicName: com.ibm.cicsdev.jzostest
Bundle-RequiredExecutionEnvironment: JavaSE-1.7
Bundle-Version: 1.0.0
Import-Package: com.ibm.cics.server;version="[1.300.0,2.0.0)",
 com.ibm.jzos.fields;resolution:=optional
Bundle-ClassPath: lib/EDUPGM.jar,
 .
CICS-MainClass: com.ibm.cicsdev.jzostest.JZOSprog
Export-Package: com.ibm.cicsdev.jzostest

**Comment by PhilWakelin** [comment]
The issue you see with ‘java.lang.NoClassDefFoundError” for JZOSCommareaWrapper is because the build/export of the Eclipse bundle project is not adding the lib/EDUPGM.jar to the project build. 

To address this, if you are using an OSGi plugin project (via wizard New -> Plug-in Development -> Plug-in Project) you should ensure the bin.includes line in your build.properties file specifies that the JAR is to be added to the build. You can do this via the Build tab in the manifest editor, and then the build.properties would look like this:
bin.includes = META-INF/,\
.,\
lib/

If you are using an OSGi bundle project (via wizard New -> OSGi -> OSGi Bundle Project) then you can just copy the EDUPGM.jar into the BundleContent folder and the build.properties should reflect this.

The alternative as you suggest is to to add the built Java Record class (or source) directly into the OSGi bundle project, as all the packages in an OSGi bundle will be visible to all components)

To address this, the repo has been restructured to provide the complete Eclipse project structure.

**Comment by ebarkow** [comment]
Thank you Phil.  I finally got it to work properly by adding EDUPGM.jar to the BundleContent and setting build.properties  as follows:

bin.includes = EDUPGM.jar,\
               META-INF/MANIFEST.MF,\
               OSGI-INF/l10n/bundle.properties,\
               build.properties
jars.compile.order = EDUPGM.jar
src.includes = EDUPGM.jar,\
               META-INF/,\
               OSGI-INF/,\
               build.properties
source=EDUPGM.jar
